<#
.SYNOPSIS
    Minimal PowerShell App Deployment Toolkit function library for pkgprobe.
.DESCRIPTION
    Provides the essential PSADT functions used by Deploy-Application.ps1:
      - Write-Log
      - Show-InstallationWelcome  (close-apps prompt)
      - Show-InstallationProgress (progress dialog)
      - Close-InstallationProgress
      - Execute-Process           (run installer with logging)
      - Show-InstallationPrompt   (user prompt)
      - Exit-Script               (clean exit)

    This is a self-contained subset inspired by PSADT v3.x (Apache License 2.0).
    It does NOT require the full PSADT distribution.
.NOTES
    Generated by pkgprobe for Intune Win32 auto-wrap packaging.
#>

[CmdletBinding()]
param()

$script:LogFile     = $null
$script:ExitCode    = 0
$script:ProgressJob = $null

# ---------------------------------------------------------------------------
# Write-Log
# ---------------------------------------------------------------------------
function Write-Log {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$Message,
        [ValidateSet('Info','Warning','Error')][string]$Severity = 'Info'
    )
    $ts = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    $line = "$ts [$Severity] $Message"
    Write-Host $line
    if ($script:LogFile) {
        try { $line | Out-File -FilePath $script:LogFile -Append -Encoding utf8 } catch {}
    }
}

# ---------------------------------------------------------------------------
# Initialize-Logging
# ---------------------------------------------------------------------------
function Initialize-Logging {
    [CmdletBinding()]
    param([string]$AppName = 'PkgProbeWrap')
    $logDir = Join-Path $env:windir 'Logs\Software'
    if (-not (Test-Path $logDir)) {
        try { New-Item -Path $logDir -ItemType Directory -Force | Out-Null } catch {}
    }
    $script:LogFile = Join-Path $logDir "$AppName`_Deploy.log"
    Write-Log "=== pkgprobe PSADT wrapper started ==="
}

# ---------------------------------------------------------------------------
# Show-InstallationWelcome
# ---------------------------------------------------------------------------
function Show-InstallationWelcome {
    [CmdletBinding()]
    param(
        [string]$CloseApps = '',
        [switch]$Silent,
        [int]$CloseAppsCountdown = 60,
        [switch]$ForceCloseAppsCountdown,
        [switch]$CheckDiskSpace,
        [switch]$PersistPrompt,
        [int]$DeferTimes = 0,
        [int]$DeferDays = 0,
        [switch]$BlockExecution
    )
    if (-not $CloseApps) { return }
    $apps = $CloseApps -split ','
    foreach ($app in $apps) {
        $app = $app.Trim()
        if (-not $app) { continue }
        $procs = Get-Process -Name $app -ErrorAction SilentlyContinue
        if ($procs) {
            Write-Log "Closing process: $app ($($procs.Count) instance(s))"
            $procs | ForEach-Object {
                try { $_.CloseMainWindow() | Out-Null } catch {}
            }
            Start-Sleep -Seconds 2
            $remaining = Get-Process -Name $app -ErrorAction SilentlyContinue
            if ($remaining) {
                Write-Log "Force-stopping: $app"
                $remaining | Stop-Process -Force -ErrorAction SilentlyContinue
            }
        }
    }
}

# ---------------------------------------------------------------------------
# Show-InstallationProgress
# ---------------------------------------------------------------------------
function Show-InstallationProgress {
    [CmdletBinding()]
    param(
        [string]$StatusMessage = 'Installation in progress. Please wait...'
    )
    Write-Log "Progress: $StatusMessage"
}

function Close-InstallationProgress {
    [CmdletBinding()]
    param()
    Write-Log 'Progress dialog closed.'
}

# ---------------------------------------------------------------------------
# Execute-Process
# ---------------------------------------------------------------------------
function Execute-Process {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$Path,
        [string]$Parameters = '',
        [switch]$WaitForMsiExec,
        [int[]]$IgnoreExitCodes = @(),
        [switch]$PassThru,
        [switch]$NoWait
    )
    Write-Log "Execute-Process: $Path $Parameters"

    $psi = New-Object System.Diagnostics.ProcessStartInfo
    $psi.FileName  = $Path
    $psi.Arguments = $Parameters
    $psi.UseShellExecute = $false
    $psi.RedirectStandardOutput = $true
    $psi.RedirectStandardError  = $true

    $proc = [System.Diagnostics.Process]::Start($psi)

    if (-not $NoWait) {
        $proc.WaitForExit()
        $ec = $proc.ExitCode
        $stdout = $proc.StandardOutput.ReadToEnd()
        $stderr = $proc.StandardError.ReadToEnd()

        if ($stdout) { Write-Log "STDOUT: $($stdout.Substring(0, [Math]::Min(2000, $stdout.Length)))" }
        if ($stderr) { Write-Log "STDERR: $($stderr.Substring(0, [Math]::Min(2000, $stderr.Length)))" -Severity Warning }
        Write-Log "Exit code: $ec"

        if ($ec -ne 0 -and $IgnoreExitCodes -notcontains $ec) {
            if ($ec -eq 3010) {
                Write-Log 'Exit code 3010: reboot required.' -Severity Warning
            } elseif ($ec -eq 1641) {
                Write-Log 'Exit code 1641: reboot initiated by installer.' -Severity Warning
            } else {
                Write-Log "Non-zero exit code: $ec" -Severity Error
            }
        }

        if ($PassThru) { return $proc }
        return $ec
    }

    if ($PassThru) { return $proc }
}

# ---------------------------------------------------------------------------
# Show-InstallationPrompt
# ---------------------------------------------------------------------------
function Show-InstallationPrompt {
    [CmdletBinding()]
    param(
        [string]$Message = '',
        [string]$ButtonRightText = 'OK',
        [string]$ButtonLeftText = '',
        [string]$ButtonMiddleText = '',
        [switch]$PersistPrompt,
        [int]$Timeout = 0
    )
    if ($Message) { Write-Log "Prompt: $Message" }
}

# ---------------------------------------------------------------------------
# Exit-Script
# ---------------------------------------------------------------------------
function Exit-Script {
    [CmdletBinding()]
    param([int]$ExitCode = 0)
    Close-InstallationProgress
    Write-Log "=== pkgprobe PSADT wrapper exiting with code $ExitCode ==="
    exit $ExitCode
}
